### ISSUE TITLE
How change text size (Label and Textfield)?

### ISSUE THREAD

**Issue by juanagu** [NadsonFernando/input-materialdesign-widget#13]

**Comment by nadsonfernando** [comment]
hello , there is this implemented user function , but can easily be implemented by creating a new attribute or a setFont .

**Comment by juanagu** [comment]
@NadsonFernando Yes I try adding a new attribute but the widget height cut textfield, I'll invest a little more time modifying the widget.

**Comment by NadsonFernando** [comment]
I based on Google's part , but if you prefer to change anything , it will vontande , I'll see here if it is appropriate and can upgrade .

**Comment by nadsonfernando** [comment]
I based on Google's part , but if you prefer to change anything , is at ease , I will see here if it is appropriate and can upgrade .
