### ISSUE TITLE
Lag on show up?

### ISSUE THREAD

**Issue by DouglasHennrich** [NadsonFernando/input-materialdesign-widget#2]
It's just for me or somebody else is facing some lag, delay, when tried to open an window that have some of this widget?

Nice Widget by the way
Thanks

**Comment by nadsonfernando** [comment]
Well, I tested , performance, and is not catching no, realized in a 6 iphone , ipad mini, and nexus 5 ( android : lollipop )
as are instantiating the widget ?, by xm or controller . Can sometimes be a problem somewhere else , send me your code to analyze. Thanks!

**Comment by DouglasHennrich** [comment]
I was using xml to create them but due this strange delay I remove it and move on with my code... so I don't have the code anymore to show you =/
another thing I do was expose the focus and blur method to be called on my .js files
eg : when I want to focus the next field from "return" button of the previous.
don't know if this could be the problem... =)

**Comment by nadsonfernando** [comment]
The thing is, this widget is nothing more than a textfield , the projects I do, always use widget, and never catches anything , it's normal , but you are free to Mecher the widget if you want to add something , some method will be more , It is ' cause I'm kind of out of time , I made this quick widget, more could improve more , who knows more now on :)

**Comment by NadsonFernando** [comment]
Fala Douglas,
blz
fui olhar seu git hub e notei que voçê tambem era do Brasil
e estavamos conversando em inglês
kkkkk ☺
você*
abre um houngouts la


2015-07-17 14:37 GMT-03:00 Douglas Hennrich <notifications@github.com>:

> I was using xml to create them but due this strange delay I remove it and
> move on with my code... so I don't have the code anymore to show you =/
> another thing I do was expose the focus and blur method to be called on my
> .js files
> eg : when I want to focus the next field from "return" button of the
> previous.
> don't know if this could be the problem... =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NadsonFernando/input-materialdesign-widget/issues/2#issuecomment-122350470>
> .
>



-- 
Boas Festas .

**Comment by DouglasHennrich** [comment]
uhauheauhaeue aí é complicado mesmo aeuhaeuhea
Tentei te achar no hangout mas nao consegui descobrir qual dos nadson fernando era vc =X
tenta me achar la: Douglas Hennrich
